/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
    
    id("com.gradleup.shadow") version "9.3.2"
    id("org.beryx.runtime") version "2.0.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
    applicationName = "softwarelifecycle"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

runtime {
	options = listOf(
		"--strip-debug",
		"--compress",
		"2",
		"--no-header-files",
		"--no-man-pages"
	)
	
	launcher {
		jvmArgs = listOf("-Xmx512m")
		runInBinDir = true
	}
	
	jpackage {
		installerType = "deb"
		installerName = "softwarelifecycle"
		imageName = "softwarelifecycle"
        appVersion = project.version.toString()

        installerOptions = listOf(
            "--vendor", "Kardonok",
            "--description", "Software Lifecycle codelab",
            "--linux-package-name", "softwarelifecycle",
            "--linux-deb-maintainer", "openmailforeveryone@gmail.com",
        )
        
        jvmArgs = listOf("-Xmx512m")
        outputDir = "DebPackages"
        resourceDir = file("src/deb")
	}
}

