name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run tests
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Build project
        run: ./gradlew build

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Create deb package
        run: ./gradlew jpackage

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: app/build/DebPackages/*.deb

  docker:
    runs-on: ubuntu-latest
    needs: package
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Download deb package
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: app/build/DebPackages

      - name: Build docker image
        run: docker build -t softwarelifecycle:1.0 .

      - name: Test docker image
        run: docker run --rm softwarelifecycle:1.0

      - name: Log in to dockerhub
        if: ${{ env.DOCKER_USERNAME && env.DOCKER_PASSWORD }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image
        if: ${{ env.DOCKER_USERNAME && env.DOCKER_PASSWORD }}
        run: |
          docker tag softwarelifecycle:1.0 ${{ secrets.DOCKER_USERNAME }}/softwarelifecycle:1.0
          docker push ${{ secrets.DOCKER_USERNAME }}/softwarelifecycle:1.0
